<?php
/* Author: Petr Hendl */

$labels = array();
$labels['removeall'] = 'Smazat všechny přílohy';
$labels['removeattachment'] = 'Smazat přílohu';

$messages = array();
$messages['removeoneconfirm'] = 'Jste si jist, že chcete smazat tuto přílohu?';
$messages['removeallconfirm'] = 'Jste si jist, že chcete smazat všechny přílohy?';
$messages['removing'] = 'Odstraňuji přílohy...';
$messages['attachmentremoved'] = 'Příloha (přílohy) byly smazány.';
$messages['removefailed'] = 'Chyba: Nepodařilo se smazat jednu nebo více příloh.';

?>
