<?php
/* Author: Philip Weir */

$labels = array();
$labels['removeall'] = 'Borrar todos los adjuntos';
$labels['removeattachment'] = 'Borrar este adjunto';

$messages = array();
$messages['removeoneconfirm'] = '¿Estás seguro/a de querer borrar este adjunto?';
$messages['removeallconfirm'] = '¿Estás seguro/a de querer borrar todos los adjuntos?';
$messages['removing'] = 'Borrando adjunto(s)...';
$messages['attachmentremoved'] = 'Adjunto(s) borrado';
$messages['removefailed'] = 'Error: No se pudo borrar el adjunto(s)';

?>
