<?php
/* Author: Jérôme Dubois */

$labels = array();
$labels['removeall'] = 'Supprimer toutes les pièces jointes';
$labels['removeattachment'] = 'Supprimer cette pièce jointe';

$messages = array();
$messages['removeoneconfirm'] = 'Êtes-vous sûr de vouloir supprimer cette pièce jointe ?';
$messages['removeallconfirm'] = 'Êtes-vous sûr de vouloir supprimer toutes les pièces jointes ?';
$messages['removing'] = 'Suppression de pièce(s) jointe(s) en cours ...';
$messages['attachmentremoved'] = 'Pièce(s) jointe(s) supprimée(s)';
$messages['removefailed'] = 'Erreur : impossible de supprimer la ou les pièces jointes';

?>
