<?php
/* Author: Balázs Dura-Kovács */

$labels = array();
$labels['removeall'] = 'Összes csatolmány törlése';
$labels['removeattachment'] = 'Csatolmány törlése';

$messages = array();
$messages['removeoneconfirm'] = 'Biztosan törli ezt a csatolmányt?';
$messages['removeallconfirm'] = 'Biztosan törli az összes csatolmányt?';
$messages['removing'] = 'Csatolmány(ok) törlése...';
$messages['attachmentremoved'] = 'Csatolmány(ok) törölve';
$messages['removefailed'] = 'Hiba: nem sikerült törölni a csatolmány(oka)t';

?>