<?php
/* Author: Gianluca Giacometti */

$labels = array();
$labels['removeall'] = 'Rimuovi tutti gli allegati';
$labels['removeattachment'] = 'Rimuovi questo allegato';

$messages = array();
$messages['removeoneconfirm'] = 'Sei sicura/o di voler rimuovere questo allegato?';
$messages['removeallconfirm'] = 'Sei sicura/o di voler rimuovere tutti gli allegati?';
$messages['removing'] = 'Allegato(i) in fase di rimozione...';
$messages['attachmentremoved'] = 'Allegato(i) rimosso(i)';
$messages['removefailed'] = 'Errore: Rimozione allegato(i) non riuscita';

?>
