<?php
/* Author: Claudio Ferreira Filho */

$labels = array();
$labels['removeall'] = 'Remover todos os anexos';
$labels['removeattachment'] = 'Remover este anexo';

$messages = array();
$messages['removeoneconfirm'] = 'Tem certeza que quer remover este anexo?';
$messages['removeallconfirm'] = 'Tem certeza que quer remover todos os anexos?';
$messages['removing'] = 'A remover o(s) anexo(s)...';
$messages['attachmentremoved'] = 'Anexo(s) removido(s)';
$messages['removefailed'] = 'Erro: Não foi possível remover o(s) anexo(s)';

?>
