<?php
/* Author: Vitaly Lipatov <lav@etersoft.ru> */

$labels = array();
$labels['removeall'] = 'Удалить все вложения';
$labels['removeattachment'] = 'Удалить';

$messages = array();
$messages['removeoneconfirm'] = 'Вы уверены, что хотите удалить это вложение?';
$messages['removeallconfirm'] = 'Вы уверены, что хотите удалить эти вложения?';
$messages['removing'] = 'Удаление вложений...';
$messages['attachmentremoved'] = 'Вложения удалены';
$messages['removefailed'] = 'Ошибка: не удалось удалить вложения';

?>
